kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.12.5-stretch
  commands:
  - go vet ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: test
  pull: always
  image: golang:1.12.5-stretch
  commands:
  - go test -cover ./...
  environment:
    GO111MODULE: on
  volumes:
  - name: gopath
    path: /go

- name: publish  
  image: plugins/ecr
  secrets: [aws_access_key_id, aws_secret_access_key]
  environment:
    ACCOUNT_ID:
      from_secret: account_id
  settings:
    repo: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/webapi
    registry: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com

volumes:
- name: gopath
  temp: {}
